Repository checkmarble/marble-frontend, pull requests merged in 2025-03, with the labels that each got.

#714 OpenAPI: add the match enrichment API.
  packages/marble-api/openapis/marblecore-api.yaml
  packages/marble-api/openapis/marblecore-api/sanction-checks.yml
  packages/marble-api/src/generated/marblecore-api.ts
Labels: enhancement

#738 Try and extract error message from ingestion error.
  packages/app-builder/src/routes/_builder+/upload+/$objectType.tsx
Labels: enhancement

#747 Chore/improve getting started
  .tool-versions
  README.md
Labels: documentation

#749 Fix rule snooze gating using webhook entitlement.
  packages/app-builder/src/models/license.ts
Labels: bug

#765 Add Case Assignment API spec.
  packages/marble-api/openapis/marblecore-api.yaml
  packages/marble-api/openapis/marblecore-api/_schemas.yml
  packages/marble-api/openapis/marblecore-api/cases.yml
  packages/marble-api/src/generated/marblecore-api.ts
Labels: enhancement

#766 Add case assignee to case DTO.
  packages/marble-api/openapis/marblecore-api/cases.yml
  packages/marble-api/src/generated/marblecore-api.ts
Labels: enhancement
